Add support for "reconnect" status
kurago-dev/node-red-contrib-opcua pull request #1
Opened 2023-02-27 08:25 UTC by aitor-gamarra

With this PR, the node will show a reconnect status similar to that of the OPC-UA Client whenever the `client.connect()` fails, instead of having an "Executing Method" status for as long as 10 years.

2023-02-27 14:04 UTC, unaipme requested changes
I also wanted to ask: This implementation only updates the node status right? The reconnection mechanism is handled automatically by the underlying OPC-UA (or whatever) library, right?

2023-02-27 14:04 UTC, unaipme commented on opcua/107-opcuamethod.js
> +    function set_node_status2_to(statusValue, message) {
nope. add the `message` param to the original `set_node_status_to`, set it to `""` by default so that we don't need to modify other usages of the function. then you could also change line 55 to `(statusParameter.status + " " + message).trim()` if you don't want to have a redundant whitespace

2023-02-28 11:45 UTC, aitor-gamarra commented on opcua/107-opcuamethod.js
> +      set_node_status2_to("reconnect", "re-establised");
https://dictionary.cambridge.org/es/diccionario/ingles/re-establish

2023-02-28 11:46 UTC, aitor-gamarra commented on opcua/107-opcuamethod.js
> +      set_node_status2_to("reconnect", "re-establised");
Done

2023-02-28 11:50 UTC, aitor-gamarra commented on opcua/107-opcuamethod.js
> +    function set_node_status2_to(statusValue, message) {
Ok. FINE.

2023-02-28 11:52 UTC, unaipme approved these changes

2023-02-28 11:53 UTC, merged